services:
  dependency-mount:
    image: alpine:latest
    container_name: dependency-mount
    restart: no
    dns: 192.168.1.1
    networks:
      - corevega-net
    volumes:
#      - /media/zachvp:/custom/state:ro
      - type: bind
        source: /media/zachvp
        target: /custom/state
        read_only: true
        bind:
          create_host_path: false
      - /home/zachvp/developer/docker/dependency-mount/dependency-mount.sh:/custom/scripts/dependency-mount.sh:ro
    healthcheck:
      test: ["CMD", "/bin/sh", "/custom/scripts/dependency-mount.sh", "healthcheck", "/custom/state/SOL"]
      interval: 5s
      timeout: 1m
    command: ["/bin/sh", "/custom/scripts/dependency-mount.sh", "main"]

  airsonic-linserv:
    image: lscr.io/linuxserver/airsonic-advanced:latest
    container_name: airsonic-linserv
    restart: unless-stopped
    depends_on:
      dependency-mount:
        condition: service_healthy
        restart: no
    dns: 192.168.1.1
    networks:
      - corevega-net
    volumes:
      - /srv/docker/airsonic:/config:rw
      - /media/zachvp/SOL/media/music:/music:ro
#      - type: volume
#        source: music
#        target: /music
#        read_only: true
#        bind:
#         create_host_path: false
    ports:
      - 8000:4040
      - 8001:4041 # UPnP
    environment:
      TZ: America/Denver
      PUID: 1000
      PGID: 1000

volumes:
#  name: music
  music:
    external: true

networks:
  corevega-net:
    external: true

