 version: "3.7"

services:
  reverse-proxy:
    #image: "jwilder/nginx-proxy:latest"
    image: "nginxproxy/nginx-proxy:1.4"
     
    container_name: "reverse-proxy"
    volumes:
      - "html:/usr/share/nginx/html"
      - "dhparam:/etc/nginx/dhparam"
      - "vhost:/etc/nginx/vhost.d"
      - "certs:/etc/nginx/certs"
      - "/run/docker.sock:/tmp/docker.sock:ro"
    restart: "always"
    networks:
      - "corevega-net"
    ports:
      - "80:80"
      - "443:443"

letsencrypt:
  image: "nginxproxy/acme-companion:2.2"
  container_name: "letsencrypt-proxy-helper"
  volumes:
    - "html:/usr/share/nginx/html"
    - "dhparam:/etc/nginx/dhparam"
    - "vhost:/etc/nginx/vhost.d"
    - "certs:/etc/nginx/certs"
    - "/run/docker.sock:/varl/run/docker.sock:ro"
  environment:
    NGINX_PROXY_CONTAINER: "reverse-proxy"
    DEFAULT_EMAIL: "vegaperk@gmail.com"
  restart: "always"
  depends_on:
    - "reverse_proxy"
  networks:
    - "corevega-net" 

volumes:
  certs:
  html:
  vhost:
  dhparam:

networks:
  corevega-net:
    external: true
