services:
  reverse-proxy:
    image: "nginxproxy/nginx-proxy:1.7.0"
    container_name: "reverse-proxy"
    volumes:
      - "html:/usr/share/nginx/html"
      - "dhparam:/etc/nginx/dhparam"
      - "vhost:/etc/nginx/vhost.d"
      - "certs:/etc/nginx/certs"
      - "/run/user/1000/docker.sock:/tmp/docker.sock:ro"
    environment:
      TRUST_DOWNSTREAM_PROXY: false
    restart: always
    dns: 192.168.50.1
    networks:
      - "corevega-net"
    ports:
      - "80:80"
      - "443:443"

  acme-companion:
    image: "nginxproxy/acme-companion:2.5.2"
    container_name: "acme-companion"
    volumes:
      - "html:/usr/share/nginx/html"
      - "dhparam:/etc/nginx/dhparam"
      - "vhost:/etc/nginx/vhost.d"
      - "certs:/etc/nginx/certs"
      - "/run/user/1000/docker.sock:/var/run/docker.sock:ro"
      - "/home/zachvp/.acme.sh:/etc/acme.sh"
    environment:
      NGINX_PROXY_CONTAINER: "reverse-proxy"
      DEFAULT_EMAIL: "vegaperk@gmail.com"
    restart: always
    depends_on:
      - "reverse-proxy"
    dns: 192.168.50.1
    networks:
      - "corevega-net" 

volumes:
  certs:
  html:
  vhost:
  dhparam:

networks:
  corevega-net:
    external: true
