 version: "3.7"

 services:
   reverse-proxy:
     image: "jwilder/nginx-proxy:latest"
     container_name: "reverse-proxy"
     volumes:
       - "html:/usr/share/nginx/html"
       - "dhparam:/etc/nginx/dhparam"
       - "vhost:/etc/nginx/vhost.d"
       - "certs:/etc/nginx/certs"
       - "/run/docker.sock:/tmp/docker.sock:ro"
     restart: "always"
     networks:
       - "corevega-net"
     ports:
       - "80:80"
       - "443:443"

 networks:
   corevega-net:
     external: true
